data:
  cv:
    - name: relationship
      cvterms:
        - name: is_a
          dbxref:
            accession: is_a
            db:
              name: OBO_REL
          cvtermsynonyms:
            - synonym: isa
              type:
                name: exact
                cv:
                  name: synonym_type
                dbxref:
                  accession: exact
                  db:
                    name: PomBase
            - synonym: ISA
              type:
                name: poor_synonym
                cv:
                  name: synonym_type
                dbxref:
                  accession: poor_synonym
                  db:
                    name: PomBase
        - name: part_of
          dbxref:
            accession: part_of
            db:
              name: OBO_REL
        - name: derives_from
          dbxref:
            accession: derives_from
            db:
              name: OBO_REL
    - name: sequence
      cvterms:
        - name: gene
          dbxref:
            accession: 0000704
            db:
              name: SO
        - name: mRNA
          dbxref:
            accession: 0000234
            db:
              name: SO
        - name: chromosome
          dbxref:
            accession: 0000340
            db:
              name: SO
        - name: polypeptide
          dbxref:
            accession: 0000104
            db:
              name: SO
        - name: intron
          dbxref:
            accession: 0000188
            db:
              name: SO
        - name: exon
          dbxref:
            accession: 0000147
            db:
              name: SO
        - name: region
          dbxref:
            accession: 0000001
            db:
              name: SO
        - name: long_terminal_repeat
          dbxref:
            accession: 0000268
            db:
              name: SO
        - name: repeat_region
          dbxref:
            accession: 0000657
            db:
              name: SO
        - name: tRNA
          dbxref:
            accession: 0000253
            db:
              name: SO
        - name: ncRNA
          dbxref:
            accession: 0000655
            db:
              name: SO
        - name: three_prime_UTR
          dbxref:
            accession: 0000205
            db:
              name: SO
        - name: five_prime_UTR
          dbxref:
            accession: 0000204
            db:
              name: SO
        - name: pseudogenic_transcript
          dbxref:
            accession: 0000516
            db:
              name: SO
        - name: pseudogenic_exon
          dbxref:
            accession: 0000507
            db:
              name: SO
        - name: pseudogene
          dbxref:
            accession: 0000336
            db:
              name: SO
    - name: molecular_function
      cvterms:
        - name: microtubule motor activity
          dbxref:
            accession: 0003777
            db:
              name: GO
        - name: molecular_function
          dbxref:
            accession: GO:0003674
            db:
              name: GO
    - name: cellular_component
      cvterms:
        - name: spindle
          dbxref:
            accession: 0005819
            db:
              name: GO
        - name: spindle pole body
          dbxref:
            accession: 0005816
            db:
              name: GO
    - name: biological_process
      cvterms:
        - name: transmembrane transport
          dbxref:
            accession: 0055085
            db:
              name: GO
        - name: negative regulation of transmembrane transport
          dbxref:
            accession: 0034763
            db:
              name: GO
    - name: fission_yeast_phenotype
      cvterms:
        - name: viability
          dbxref:
            accession: 0000004
            db:
              name: FYPO
    - name: PSI-MOD
    - name: feature_cvtermprop_type
      cvterms:
        - name: assigned_by
          dbxref:
            accession: 01000000
            db:
              name: PomBase
        - name: evidence
          dbxref:
            accession: 01000001
            db:
              name: PomBase
    - name: PomBase organism property types
      cvterms:
        - name: taxon_id
          dbxref:
            accession: 0000002
            db:
              name: PomBase
    - name: PomBase publication types
      cvterms:
        - name: paper
          dbxref:
            accession: 0000003
            db:
              name: PomBase
  cvterm_relationships:
    - subject:
        name: microtubule motor activity
      object:
        name: molecular_function
      type:
        name: is_a
  extra_cvterm_terms:
  db:
    - name: feature_cvtermprop_type
  pub:
    - uniquename: PMID:11739790
      type:
        name: paper
  feature:
    - uniquename: SPBC2F12.13
      name: klp5
      type:
        name: gene
      organism:
        genus: Schizosacchaomyces
        species: pombe
    - uniquename: SPBC2F12.13.1
      type:
        name: mRNA
      organism:
        genus: Schizosacchaomyces
        species: pombe
  feature_cvterm:
    - feature:
        uniquename: SPBC2F12.13
      cvterm:
        name: spindle pole body
      feature_cvtermprops:
        - type:
            name: evidence
          value: Inferred from Electronic Annotation
      pub:
        uniquename: PMID:11739790
test_organism:
  genus: Schizosaccharomyces
  species: pombe
  common_name: pombe
  taxonid: 4896

test_genes:
  - uniquename: SPBC2F12.13
  - uniquename: SPAC1093.06c
  - uniquename: SPCC576.16c
  - uniquename: SPAC27D7.13c
  - uniquename: SPCC63.05
  - uniquename: SPBC14F5.07
